server:
  port: 8090

spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:

  # 配置方言
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect